import { Octokit } from '@octokit/rest';
import parseDiff from 'parse-diff';
import { getPRDiff, getPRDetails, createReviewComment, createSummaryComment } from './github';
import { generateReview, LLMConfig } from './llm';

export async function processReview(
  octokit: Octokit,
  owner: string,
  repo: string,
  pullNumber: number,
  llmConfig: LLMConfig
) {
  console.log(`Fetching PR details for ${owner}/${repo}#${pullNumber}...`);
  const pr = await getPRDetails(octokit, owner, repo, pullNumber);
  const commitId = pr.head.sha;

  console.log('Fetching PR diff...');
  const diffString = await getPRDiff(octokit, owner, repo, pullNumber);
  
  if (!diffString) {
    console.log('No diff found.');
    return;
  }

  // Use parse-diff to understand which files and lines changed
  // @ts-ignore
  let files = parseDiff(diffString);

  // Filter out lock files and autogenerated files to save tokens
  files = files.filter((file: any) => {
    const name = file.to || file.from || '';
    return !name.match(/(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|dist\/|build\/)/);
  });

  if (files.length === 0) {
    console.log('Only lock files or ignored files changed. Skipping review.');
    return;
  }

  // Reconstruct a simplified diff string for the LLM
  let filteredDiff = '';
  for (const file of files) {
    filteredDiff += `\n--- a/${file.from || file.to}\n+++ b/${file.to || file.from}\n`;
    for (const chunk of file.chunks) {
      filteredDiff += `@@ -${chunk.oldStart},${chunk.oldLines} +${chunk.newStart},${chunk.newLines} @@\n`;
      for (const change of chunk.changes) {
        filteredDiff += `${change.content}\n`;
      }
    }
  }

  console.log('Generating review with LLM...');
  const reviewResult = await generateReview(filteredDiff, llmConfig);

  if (!reviewResult) {
    console.error('Failed to generate review.');
    return;
  }

  console.log('Posting summary comment...');
  await createSummaryComment(octokit, owner, repo, pullNumber, `## AI Code Review Summary\n\n${reviewResult.summary}`);

  console.log('Posting inline comments...');
  for (const comment of reviewResult.inlineComments) {
    try {
      // Basic check to ensure the file exists in the diff
      const fileInDiff = files.find((f: any) => f.to === comment.path || f.from === comment.path);
      if (fileInDiff) {
        await createReviewComment(
          octokit,
          owner,
          repo,
          pullNumber,
          commitId,
          comment.path,
          comment.line,
          comment.comment
        );
        console.log(`Posted comment on ${comment.path}:${comment.line}`);
      }
    } catch (error) {
      console.error(`Failed to post comment on ${comment.path}:${comment.line}:`, error);
    }
  }

  console.log('Review complete!');
}
